---
title: "Seminar 6"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# R
Reading Dataset.
```{r, results='hide', message=FALSE, warning=FALSE}
library(tidyverse)
library(haven) #чтение .dta файлов

df <- read_dta(file = "crisis.dta")
ts <- ts(df[,c("labor", "oil_b_rub", "rwage", "u")], start = c(1999, 1), end = c(2009, 12), frequency = 12)
```

```{r}
lin_m1 <- lm(ts[,"rwage"] ~ ts[,"oil_b_rub"] + ts[,"u"])
summary(lin_m1)
```

## Переделать график и добавить второй
```{r}
resid <- resid(lin_m1)
plot(time(ts), resid)
```

## Durbin-Watson test???
```{r}

```

## Breusch-Godfrey
```{r}

```

## Newey-West estimators
```{r}

```

## 3
```{r}
acf(resid, lag.max = 25)
pacf(resid, lag.max = 25)
```

## 4
```{r}
plot(ts[,"labor"])
plot(ts[,"u"])
plot(ts[,"rwage"])
plot(ts[,"oil_b_rub"])
```

## 5
### Correlograms
```{r}
acf(ts[,"labor"], lag.max = 25)
pacf(ts[,"labor"], lag.max = 25)
acf(diff(ts[,"labor"]), lag.max = 25)
pacf(diff(ts[,"labor"]), lag.max = 25)
```

```{r}
acf(ts[,"u"], lag.max = 25)
pacf(ts[,"u"], lag.max = 25)
acf(diff(ts[,"u"]), lag.max = 25)
pacf(diff(ts[,"u"]), lag.max = 25)
```

```{r}
acf(ts[,"rwage"], lag.max = 25)
pacf(ts[,"rwage"], lag.max = 25)
acf(diff(ts[,"rwage"]), lag.max = 25)
pacf(diff(ts[,"rwage"]), lag.max = 25)
```

```{r}
acf(ts[,"oil_b_rub"], lag.max = 25)
pacf(ts[,"oil_b_rub"], lag.max = 25)
acf(diff(ts[,"oil_b_rub"]), lag.max = 25)
pacf(diff(ts[,"oil_b_rub"]), lag.max = 25)
```

## 6
```{r}

```

## 7
### ARIMA models
```{r}
arima_1 <- arima(ts[,"labor"], order = c(1, 0, 1))
arima_1
```








