---
title: "Seminar 22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, results='hide', message=FALSE, warning=FALSE}
library(tidyverse)
library(haven) #чтение .dta файлов
library(car)

df <- read_dta(file = "nerlove.dta")
```

```{r}
df$lnc <- log(df$c)
df$lnq <- log(df$q)
df$lnpw <- log(df$pw)
df$lnpk <- log(df$pk)
df$lnpf <- log(df$pf)
```

## How to estimate robust variance of coefficients???
```{r}
lin_m1 <- lm(lnc ~ lnq + lnpw + lnpf + lnpk, data = df)
summary(lin_m1)
```

## Значение тестовой статистики отличается от stata
```{r}
linearHypothesis(lin_m1, "lnpw+lnpk+lnpf=1")
```

## Incorporating constraint
```{r}
df$lnck <- df$lnc - df$lnpk
df$lnpwk <- df$lnpw - df$lnpk
df$lnpfk <- df$lnpf - df$lnpk
lin_m2 <- lm(lnck ~ lnq + lnpwk + lnpfk, data = df)
summary(lin_m2)
```

## NLS 
### Не работает с начальными значениями из исходного файла, более того, выдает другие оценки
```{r}
nls_1 <- nls(lnck ~ cons_ + lnq_ * lnq + lnpwk_ * lnpwk + lnpfk_ * lnpfk + alpha6_ * lnq * (1 + exp(-(lnq - alpha7_)))^(-1), data = df)
summary(nls_1)
```

## Conventional smooth transition model
#### Почему-то выдает ошибку градиента
```{r}
nls_2 <- nls(lnck ~ cons_+lnq_ * lnq * (1 - (1 + exp(-(lnq - alpha7_)))^(-1)) + lnpwk_ * lnpwk + lnpfk_ * lnpfk + alpha6_ * lnq * (1 + exp(-(lnq - alpha7_)))^(-1), data = df)
summary(nls_2)
```






